// ---------------------------------------------------------------------------
// Quasar 检测评估实验台 · 实验室基线样本（Quasar-LabBaseline）
// 作者：陈森（Chen Sen）  https://github.com/chendashi666
// 本文件由陈森创作或改造：禁止盗卖，禁止商业用途。
// 上游 Quasar 代码版权归 MaxXor 及 Quasar 贡献者所有（MIT License）。
// ---------------------------------------------------------------------------

//------------------------------------------------------------------------------
// <auto-generated>
//     Laboratory resource accessor for the standardized baseline strings.
//     Regenerate by editing Properties\LabResources.resx and keeping this file in sync.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quasar.Common.Properties
{
    using System;
    using System.Globalization;
    using System.Resources;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("LabBaseline", "1.4.1.0")]
    public static class LabStrings
    {
        private static ResourceManager _resourceMan;
        private static CultureInfo _resourceCulture;

        internal static ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(_resourceMan, null))
                {
                    var temp = new ResourceManager("Quasar.Common.Properties.LabResources", typeof(LabStrings).Assembly);
                    _resourceMan = temp;
                }
                return _resourceMan;
            }
        }

        internal static CultureInfo Culture
        {
            get { return _resourceCulture; }
            set { _resourceCulture = value; }
        }

        private static string Get(string name)
        {
            return ResourceManager.GetString(name, _resourceCulture);
        }

        public static string LabName { get { return Get("LabName"); } }
        public static string ProductName { get { return Get("ProductName"); } }
        public static string Company { get { return Get("Company"); } }
        public static string Copyright { get { return Get("Copyright"); } }
        public static string Description { get { return Get("Description"); } }
        public static string AssemblyVersion { get { return Get("AssemblyVersion"); } }
        public static string LogMarker { get { return Get("LogMarker"); } }
        public static string ConfigFileName { get { return Get("ConfigFileName"); } }
        public static string ClientBinaryName { get { return Get("ClientBinaryName"); } }
        public static string CertificateFileName { get { return Get("CertificateFileName"); } }
        public static string NamespaceRoot { get { return Get("NamespaceRoot"); } }
        public static string ClientNamespace { get { return Get("ClientNamespace"); } }
        public static string ConfigNamespace { get { return Get("ConfigNamespace"); } }
        public static string SettingsTypeName { get { return Get("SettingsTypeName"); } }
        public static string DefaultLogDirectory { get { return Get("DefaultLogDirectory"); } }
        public static string DefaultInstallSubDirectory { get { return Get("DefaultInstallSubDirectory"); } }
        public static string DefaultClientName { get { return Get("DefaultClientName"); } }
        public static string HostsFieldHint { get { return Get("HostsFieldHint"); } }
        public static string PortFieldHint { get { return Get("PortFieldHint"); } }
        public static string MutexFieldHint { get { return Get("MutexFieldHint"); } }
        public static string TagFieldHint { get { return Get("TagFieldHint"); } }
        public static string SubnetFieldHint { get { return Get("SubnetFieldHint"); } }
    }
}